name: Build, package and test cJSON

on:
  push:
    branches: [ "ino_dev" ]
  pull_request:
    branches: [ "ino_dev" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout repo
        uses: actions/checkout@v3

      # builduje obraz, który w /tmp/install tworzy RPM i w CMD kopiuje je do /out
      - name: Build RPM image
        run: |
          docker build \
            -f docker/Dockerfile.build1 \
            -t cjson-builder-image \
            docker/

      # uruchamia builder z volume, aby CMD skopiowało RPM do artifacts
      - name: Extract RPM artifact
        run: |
          mkdir -p artifacts
          docker run --rm \
            -v $PWD/artifacts:/out \
            cjson-builder-image

      # upload RPM
      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: cjson-rpm
          path: artifacts/*.rpm

      #  buduje i odpala kontener deployowy – ma skopiować RPM, skompilować example i je odpalić
      - name: Build deploy image
        run: |
          docker build \
            -f docker/Dockerfile.deploy \
            -t cjson-deploy-image \
            docker/

      - name: Run example in deploy container
        run: |
          docker run --rm cjson-deploy-image

      # buduje i uruchamia testy przez Dockerfile.test
      - name: Build test image
        run: |
          docker build \
            -f docker/Dockerfile.test \
            -t cjson-test-image \
            docker/

      - name: Run tests
        run: |
          docker run --rm cjson-test-image

